/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ultracart.admin.v2.models/AutoOrderItem', 'com.ultracart.admin.v2.models/Order'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AutoOrderItem'), require('./Order'));
  } else {
    // Browser globals (root is window)
    if (!root.UltraCartRestApiV2) {
      root.UltraCartRestApiV2 = {};
    }
    root.UltraCartRestApiV2.AutoOrder = factory(root.UltraCartRestApiV2.ApiClient, root.UltraCartRestApiV2.AutoOrderItem, root.UltraCartRestApiV2.Order);
  }
}(this, function(ApiClient, AutoOrderItem, Order) {
  'use strict';

  /**
   * The AutoOrder model module.
   * @module com.ultracart.admin.v2.models/AutoOrder
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>AutoOrder</code>.
   * @alias module:com.ultracart.admin.v2.models/AutoOrder
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AutoOrder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ultracart.admin.v2.models/AutoOrder} obj Optional instance to populate.
   * @return {module:com.ultracart.admin.v2.models/AutoOrder} The populated <code>AutoOrder</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('auto_order_code'))
        obj.autoOrderCode = ApiClient.convertToType(data['auto_order_code'], 'String');
      if (data.hasOwnProperty('auto_order_oid'))
        obj.autoOrderOid = ApiClient.convertToType(data['auto_order_oid'], 'Number');
      if (data.hasOwnProperty('cancel_after_next_x_orders'))
        obj.cancelAfterNextXOrders = ApiClient.convertToType(data['cancel_after_next_x_orders'], 'Number');
      if (data.hasOwnProperty('cancel_downgrade'))
        obj.cancelDowngrade = ApiClient.convertToType(data['cancel_downgrade'], 'Boolean');
      if (data.hasOwnProperty('cancel_upgrade'))
        obj.cancelUpgrade = ApiClient.convertToType(data['cancel_upgrade'], 'Boolean');
      if (data.hasOwnProperty('canceled_by_user'))
        obj.canceledByUser = ApiClient.convertToType(data['canceled_by_user'], 'String');
      if (data.hasOwnProperty('canceled_dts'))
        obj.canceledDts = ApiClient.convertToType(data['canceled_dts'], 'String');
      if (data.hasOwnProperty('completed'))
        obj.completed = ApiClient.convertToType(data['completed'], 'Boolean');
      if (data.hasOwnProperty('credit_card_attempt'))
        obj.creditCardAttempt = ApiClient.convertToType(data['credit_card_attempt'], 'Number');
      if (data.hasOwnProperty('disabled_dts'))
        obj.disabledDts = ApiClient.convertToType(data['disabled_dts'], 'String');
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('failure_reason'))
        obj.failureReason = ApiClient.convertToType(data['failure_reason'], 'String');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [AutoOrderItem]);
      if (data.hasOwnProperty('next_attempt'))
        obj.nextAttempt = ApiClient.convertToType(data['next_attempt'], 'String');
      if (data.hasOwnProperty('original_order'))
        obj.originalOrder = Order.constructFromObject(data['original_order']);
      if (data.hasOwnProperty('original_order_id'))
        obj.originalOrderId = ApiClient.convertToType(data['original_order_id'], 'String');
      if (data.hasOwnProperty('override_affiliate_id'))
        obj.overrideAffiliateId = ApiClient.convertToType(data['override_affiliate_id'], 'Number');
      if (data.hasOwnProperty('rebill_orders'))
        obj.rebillOrders = ApiClient.convertToType(data['rebill_orders'], [Order]);
      if (data.hasOwnProperty('rotating_transaction_gateway_code'))
        obj.rotatingTransactionGatewayCode = ApiClient.convertToType(data['rotating_transaction_gateway_code'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }

  /**
   * Unique code assigned to this auto order
   * @member {String} autoOrderCode
   */
  exports.prototype.autoOrderCode = undefined;

  /**
   * Auto order object identifier
   * @member {Number} autoOrderOid
   */
  exports.prototype.autoOrderOid = undefined;

  /**
   * Cancel this auto order after X additional rebills
   * @member {Number} cancelAfterNextXOrders
   */
  exports.prototype.cancelAfterNextXOrders = undefined;

  /**
   * True if the auto order was canceled because the customer purchased a downgrade item
   * @member {Boolean} cancelDowngrade
   */
  exports.prototype.cancelDowngrade = undefined;

  /**
   * True if the auto order was canceled because the customer purchased an upgrade item
   * @member {Boolean} cancelUpgrade
   */
  exports.prototype.cancelUpgrade = undefined;

  /**
   * The user that canceled the auto order
   * @member {String} canceledByUser
   */
  exports.prototype.canceledByUser = undefined;

  /**
   * The date/time that the auto order was canceled
   * @member {String} canceledDts
   */
  exports.prototype.canceledDts = undefined;

  /**
   * True if the auto order ran successfully to completion
   * @member {Boolean} completed
   */
  exports.prototype.completed = undefined;

  /**
   * The number of credit card attempts that have taken place
   * @member {Number} creditCardAttempt
   */
  exports.prototype.creditCardAttempt = undefined;

  /**
   * The date/time the auto order was disabled due to failed rebills
   * @member {String} disabledDts
   */
  exports.prototype.disabledDts = undefined;

  /**
   * True if this auto order is enabled
   * @member {Boolean} enabled
   */
  exports.prototype.enabled = undefined;

  /**
   * The reason this auto order failed during the last rebill attempt
   * @member {String} failureReason
   */
  exports.prototype.failureReason = undefined;

  /**
   * The items that are setup to rebill
   * @member {Array.<module:com.ultracart.admin.v2.models/AutoOrderItem>} items
   */
  exports.prototype.items = undefined;

  /**
   * The next time that the auto order will be attempted for processing
   * @member {String} nextAttempt
   */
  exports.prototype.nextAttempt = undefined;

  /**
   * @member {module:com.ultracart.admin.v2.models/Order} originalOrder
   */
  exports.prototype.originalOrder = undefined;

  /**
   * The original order id that this auto order is associated with.
   * @member {String} originalOrderId
   */
  exports.prototype.originalOrderId = undefined;

  /**
   * Override the affiliate id given credit for rebills of this auto order
   * @member {Number} overrideAffiliateId
   */
  exports.prototype.overrideAffiliateId = undefined;

  /**
   * Rebill orders that have taken place on this auto order
   * @member {Array.<module:com.ultracart.admin.v2.models/Order>} rebillOrders
   */
  exports.prototype.rebillOrders = undefined;

  /**
   * The RTG code associated with this order for future rebills
   * @member {String} rotatingTransactionGatewayCode
   */
  exports.prototype.rotatingTransactionGatewayCode = undefined;

  /**
   * The status of the auto order
   * @member {module:com.ultracart.admin.v2.models/AutoOrder.StatusEnum} status
   */
  exports.prototype.status = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "active"
     * @const
     */
    active: "active",

    /**
     * value: "canceled"
     * @const
     */
    canceled: "canceled",

    /**
     * value: "disabled"
     * @const
     */
    disabled: "disabled"
  };

  return exports;

}));
