/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AutoOrderConsolidate model module.
 * @module com.ultracart.admin.v2.models/AutoOrderConsolidate
 * @version 4.1.18
 */
class AutoOrderConsolidate {
    /**
     * Constructs a new <code>AutoOrderConsolidate</code>.
     * @alias module:com.ultracart.admin.v2.models/AutoOrderConsolidate
     */
    constructor() { 
        
        AutoOrderConsolidate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AutoOrderConsolidate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/AutoOrderConsolidate} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/AutoOrderConsolidate} The populated <code>AutoOrderConsolidate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AutoOrderConsolidate();

            if (data.hasOwnProperty('source_auto_order_oids')) {
                obj['source_auto_order_oids'] = ApiClient.convertToType(data['source_auto_order_oids'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} source_auto_order_oids
 */
AutoOrderConsolidate.prototype['source_auto_order_oids'] = undefined;






export default AutoOrderConsolidate;

