/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UltraCartRestApiV2) {
      root.UltraCartRestApiV2 = {};
    }
    root.UltraCartRestApiV2.ConversationPbxCallTranscriptSegment = factory(root.UltraCartRestApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ConversationPbxCallTranscriptSegment model module.
   * @module com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment
   * @version 3.11.66
   */

  /**
   * Constructs a new <code>ConversationPbxCallTranscriptSegment</code>.
   * @alias module:com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ConversationPbxCallTranscriptSegment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment} obj Optional instance to populate.
   * @return {module:com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment} The populated <code>ConversationPbxCallTranscriptSegment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('agent_id'))
        obj.agent_id = ApiClient.convertToType(data['agent_id'], 'String');
      if (data.hasOwnProperty('channel'))
        obj.channel = ApiClient.convertToType(data['channel'], 'String');
      if (data.hasOwnProperty('confidence'))
        obj.confidence = ApiClient.convertToType(data['confidence'], 'Number');
      if (data.hasOwnProperty('end_time'))
        obj.end_time = ApiClient.convertToType(data['end_time'], 'Number');
      if (data.hasOwnProperty('speaker'))
        obj.speaker = ApiClient.convertToType(data['speaker'], 'String');
      if (data.hasOwnProperty('start_time'))
        obj.start_time = ApiClient.convertToType(data['start_time'], 'Number');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }

  /**
   * Agent ID if speaker is an agent
   * @member {String} agent_id
   */
  exports.prototype.agent_id = undefined;

  /**
   * Audio channel identifier (e.g. ch_0, ch_1)
   * @member {String} channel
   */
  exports.prototype.channel = undefined;

  /**
   * Transcription confidence score (0-1)
   * @member {Number} confidence
   */
  exports.prototype.confidence = undefined;

  /**
   * End time in seconds from beginning of recording
   * @member {Number} end_time
   */
  exports.prototype.end_time = undefined;

  /**
   * Speaker role
   * @member {module:com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment.SpeakerEnum} speaker
   */
  exports.prototype.speaker = undefined;

  /**
   * Start time in seconds from beginning of recording
   * @member {Number} start_time
   */
  exports.prototype.start_time = undefined;

  /**
   * Transcribed text for this segment
   * @member {String} text
   */
  exports.prototype.text = undefined;


  /**
   * Allowed values for the <code>speaker</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SpeakerEnum = {
    /**
     * value: "customer"
     * @const
     */
    customer: "customer",

    /**
     * value: "agent"
     * @const
     */
    agent: "agent"
  };

  return exports;

}));
