/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConversationPbxCallTranscriptSegment model module.
 * @module com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment
 * @version 4.1.60
 */
class ConversationPbxCallTranscriptSegment {
    /**
     * Constructs a new <code>ConversationPbxCallTranscriptSegment</code>.
     * @alias module:com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment
     */
    constructor() { 
        
        ConversationPbxCallTranscriptSegment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConversationPbxCallTranscriptSegment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment} The populated <code>ConversationPbxCallTranscriptSegment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConversationPbxCallTranscriptSegment();

            if (data.hasOwnProperty('agent_id')) {
                obj['agent_id'] = ApiClient.convertToType(data['agent_id'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'Number');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'Number');
            }
            if (data.hasOwnProperty('speaker')) {
                obj['speaker'] = ApiClient.convertToType(data['speaker'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Number');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Agent ID if speaker is an agent
 * @member {String} agent_id
 */
ConversationPbxCallTranscriptSegment.prototype['agent_id'] = undefined;

/**
 * Audio channel identifier (e.g. ch_0, ch_1)
 * @member {String} channel
 */
ConversationPbxCallTranscriptSegment.prototype['channel'] = undefined;

/**
 * Transcription confidence score (0-1)
 * @member {Number} confidence
 */
ConversationPbxCallTranscriptSegment.prototype['confidence'] = undefined;

/**
 * End time in seconds from beginning of recording
 * @member {Number} end_time
 */
ConversationPbxCallTranscriptSegment.prototype['end_time'] = undefined;

/**
 * Speaker role
 * @member {module:com.ultracart.admin.v2.models/ConversationPbxCallTranscriptSegment.SpeakerEnum} speaker
 */
ConversationPbxCallTranscriptSegment.prototype['speaker'] = undefined;

/**
 * Start time in seconds from beginning of recording
 * @member {Number} start_time
 */
ConversationPbxCallTranscriptSegment.prototype['start_time'] = undefined;

/**
 * Transcribed text for this segment
 * @member {String} text
 */
ConversationPbxCallTranscriptSegment.prototype['text'] = undefined;





/**
 * Allowed values for the <code>speaker</code> property.
 * @enum {String}
 * @readonly
 */
ConversationPbxCallTranscriptSegment['SpeakerEnum'] = {

    /**
     * value: "customer"
     * @const
     */
    "customer": "customer",

    /**
     * value: " agent"
     * @const
     */
    " agent": " agent"
};



export default ConversationPbxCallTranscriptSegment;

