/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UltraCartRestApiV2) {
      root.UltraCartRestApiV2 = {};
    }
    root.UltraCartRestApiV2.ConversationPbxCallAgent = factory(root.UltraCartRestApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ConversationPbxCallAgent model module.
   * @module com.ultracart.admin.v2.models/ConversationPbxCallAgent
   * @version 3.11.61
   */

  /**
   * Constructs a new <code>ConversationPbxCallAgent</code>.
   * @alias module:com.ultracart.admin.v2.models/ConversationPbxCallAgent
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ConversationPbxCallAgent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ultracart.admin.v2.models/ConversationPbxCallAgent} obj Optional instance to populate.
   * @return {module:com.ultracart.admin.v2.models/ConversationPbxCallAgent} The populated <code>ConversationPbxCallAgent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('agent_extension'))
        obj.agent_extension = ApiClient.convertToType(data['agent_extension'], 'String');
      if (data.hasOwnProperty('agent_id'))
        obj.agent_id = ApiClient.convertToType(data['agent_id'], 'String');
      if (data.hasOwnProperty('agent_name'))
        obj.agent_name = ApiClient.convertToType(data['agent_name'], 'String');
      if (data.hasOwnProperty('answered'))
        obj.answered = ApiClient.convertToType(data['answered'], 'Boolean');
      if (data.hasOwnProperty('call_sid'))
        obj.call_sid = ApiClient.convertToType(data['call_sid'], 'String');
      if (data.hasOwnProperty('joined_at_dts'))
        obj.joined_at_dts = ApiClient.convertToType(data['joined_at_dts'], 'String');
      if (data.hasOwnProperty('left_at_dts'))
        obj.left_at_dts = ApiClient.convertToType(data['left_at_dts'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('worker_sid'))
        obj.worker_sid = ApiClient.convertToType(data['worker_sid'], 'String');
    }
    return obj;
  }

  /**
   * Agent's phone extension
   * @member {String} agent_extension
   */
  exports.prototype.agent_extension = undefined;

  /**
   * Unique identifier for the agent
   * @member {String} agent_id
   */
  exports.prototype.agent_id = undefined;

  /**
   * Display name of the agent
   * @member {String} agent_name
   */
  exports.prototype.agent_name = undefined;

  /**
   * Whether the agent answered the call
   * @member {Boolean} answered
   */
  exports.prototype.answered = undefined;

  /**
   * Twilio call SID for the agent's call leg
   * @member {String} call_sid
   */
  exports.prototype.call_sid = undefined;

  /**
   * Timestamp when the agent joined the call
   * @member {String} joined_at_dts
   */
  exports.prototype.joined_at_dts = undefined;

  /**
   * Timestamp when the agent left the call
   * @member {String} left_at_dts
   */
  exports.prototype.left_at_dts = undefined;

  /**
   * Role of the agent in the call
   * @member {String} role
   */
  exports.prototype.role = undefined;

  /**
   * Twilio TaskRouter worker SID
   * @member {String} worker_sid
   */
  exports.prototype.worker_sid = undefined;

  return exports;

}));
