/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConversationPbxCallAgent from './ConversationPbxCallAgent';
import ConversationPbxCallAiEngagement from './ConversationPbxCallAiEngagement';
import ConversationPbxCallCaller from './ConversationPbxCallCaller';
import ConversationPbxCallFinancial from './ConversationPbxCallFinancial';
import ConversationPbxCallHold from './ConversationPbxCallHold';
import ConversationPbxCallRecording from './ConversationPbxCallRecording';
import ConversationPbxCallRouting from './ConversationPbxCallRouting';
import ConversationPbxCallTimeline from './ConversationPbxCallTimeline';
import ConversationPbxCallTransfer from './ConversationPbxCallTransfer';

/**
 * The ConversationPbxCall model module.
 * @module com.ultracart.admin.v2.models/ConversationPbxCall
 * @version 4.1.63
 */
class ConversationPbxCall {
    /**
     * Constructs a new <code>ConversationPbxCall</code>.
     * @alias module:com.ultracart.admin.v2.models/ConversationPbxCall
     */
    constructor() { 
        
        ConversationPbxCall.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConversationPbxCall</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/ConversationPbxCall} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/ConversationPbxCall} The populated <code>ConversationPbxCall</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConversationPbxCall();

            if (data.hasOwnProperty('account_sid')) {
                obj['account_sid'] = ApiClient.convertToType(data['account_sid'], 'String');
            }
            if (data.hasOwnProperty('agents')) {
                obj['agents'] = ApiClient.convertToType(data['agents'], [ConversationPbxCallAgent]);
            }
            if (data.hasOwnProperty('ai_agent_engagements')) {
                obj['ai_agent_engagements'] = ApiClient.convertToType(data['ai_agent_engagements'], [ConversationPbxCallAiEngagement]);
            }
            if (data.hasOwnProperty('call_sid')) {
                obj['call_sid'] = ApiClient.convertToType(data['call_sid'], 'String');
            }
            if (data.hasOwnProperty('call_uuid')) {
                obj['call_uuid'] = ApiClient.convertToType(data['call_uuid'], 'String');
            }
            if (data.hasOwnProperty('caller')) {
                obj['caller'] = ConversationPbxCallCaller.constructFromObject(data['caller']);
            }
            if (data.hasOwnProperty('conference_sid')) {
                obj['conference_sid'] = ApiClient.convertToType(data['conference_sid'], 'String');
            }
            if (data.hasOwnProperty('created_at_dts')) {
                obj['created_at_dts'] = ApiClient.convertToType(data['created_at_dts'], 'String');
            }
            if (data.hasOwnProperty('customer_name')) {
                obj['customer_name'] = ApiClient.convertToType(data['customer_name'], 'String');
            }
            if (data.hasOwnProperty('customer_profile_oid')) {
                obj['customer_profile_oid'] = ApiClient.convertToType(data['customer_profile_oid'], 'String');
            }
            if (data.hasOwnProperty('disposition')) {
                obj['disposition'] = ApiClient.convertToType(data['disposition'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('financial')) {
                obj['financial'] = ConversationPbxCallFinancial.constructFromObject(data['financial']);
            }
            if (data.hasOwnProperty('holds')) {
                obj['holds'] = ApiClient.convertToType(data['holds'], [ConversationPbxCallHold]);
            }
            if (data.hasOwnProperty('merchant_id')) {
                obj['merchant_id'] = ApiClient.convertToType(data['merchant_id'], 'String');
            }
            if (data.hasOwnProperty('recording_sids')) {
                obj['recording_sids'] = ApiClient.convertToType(data['recording_sids'], ['String']);
            }
            if (data.hasOwnProperty('recordings')) {
                obj['recordings'] = ApiClient.convertToType(data['recordings'], [ConversationPbxCallRecording]);
            }
            if (data.hasOwnProperty('routing')) {
                obj['routing'] = ConversationPbxCallRouting.constructFromObject(data['routing']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('timeline')) {
                obj['timeline'] = ConversationPbxCallTimeline.constructFromObject(data['timeline']);
            }
            if (data.hasOwnProperty('transfers')) {
                obj['transfers'] = ApiClient.convertToType(data['transfers'], [ConversationPbxCallTransfer]);
            }
            if (data.hasOwnProperty('updated_at_dts')) {
                obj['updated_at_dts'] = ApiClient.convertToType(data['updated_at_dts'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Twilio account SID
 * @member {String} account_sid
 */
ConversationPbxCall.prototype['account_sid'] = undefined;

/**
 * List of agents who participated in this call
 * @member {Array.<module:com.ultracart.admin.v2.models/ConversationPbxCallAgent>} agents
 */
ConversationPbxCall.prototype['agents'] = undefined;

/**
 * List of AI agent engagements during the call
 * @member {Array.<module:com.ultracart.admin.v2.models/ConversationPbxCallAiEngagement>} ai_agent_engagements
 */
ConversationPbxCall.prototype['ai_agent_engagements'] = undefined;

/**
 * Twilio call SID for the primary (customer) call leg
 * @member {String} call_sid
 */
ConversationPbxCall.prototype['call_sid'] = undefined;

/**
 * Unique identifier for this call record
 * @member {String} call_uuid
 */
ConversationPbxCall.prototype['call_uuid'] = undefined;

/**
 * @member {module:com.ultracart.admin.v2.models/ConversationPbxCallCaller} caller
 */
ConversationPbxCall.prototype['caller'] = undefined;

/**
 * Twilio conference SID if this call used conferencing
 * @member {String} conference_sid
 */
ConversationPbxCall.prototype['conference_sid'] = undefined;

/**
 * Timestamp when the call record was created
 * @member {String} created_at_dts
 */
ConversationPbxCall.prototype['created_at_dts'] = undefined;

/**
 * Customer name associated with this call
 * @member {String} customer_name
 */
ConversationPbxCall.prototype['customer_name'] = undefined;

/**
 * UltraCart customer profile OID if the caller was matched to a customer
 * @member {String} customer_profile_oid
 */
ConversationPbxCall.prototype['customer_profile_oid'] = undefined;

/**
 * Call disposition describing how the call ended
 * @member {String} disposition
 */
ConversationPbxCall.prototype['disposition'] = undefined;

/**
 * Email address of the caller if known
 * @member {String} email
 */
ConversationPbxCall.prototype['email'] = undefined;

/**
 * @member {module:com.ultracart.admin.v2.models/ConversationPbxCallFinancial} financial
 */
ConversationPbxCall.prototype['financial'] = undefined;

/**
 * List of hold events during the call
 * @member {Array.<module:com.ultracart.admin.v2.models/ConversationPbxCallHold>} holds
 */
ConversationPbxCall.prototype['holds'] = undefined;

/**
 * Merchant identifier
 * @member {String} merchant_id
 */
ConversationPbxCall.prototype['merchant_id'] = undefined;

/**
 * List of all Twilio recording SIDs associated with this call
 * @member {Array.<String>} recording_sids
 */
ConversationPbxCall.prototype['recording_sids'] = undefined;

/**
 * List of recordings made during the call
 * @member {Array.<module:com.ultracart.admin.v2.models/ConversationPbxCallRecording>} recordings
 */
ConversationPbxCall.prototype['recordings'] = undefined;

/**
 * @member {module:com.ultracart.admin.v2.models/ConversationPbxCallRouting} routing
 */
ConversationPbxCall.prototype['routing'] = undefined;

/**
 * Final status of the call
 * @member {String} status
 */
ConversationPbxCall.prototype['status'] = undefined;

/**
 * @member {module:com.ultracart.admin.v2.models/ConversationPbxCallTimeline} timeline
 */
ConversationPbxCall.prototype['timeline'] = undefined;

/**
 * List of transfer events during the call
 * @member {Array.<module:com.ultracart.admin.v2.models/ConversationPbxCallTransfer>} transfers
 */
ConversationPbxCall.prototype['transfers'] = undefined;

/**
 * Timestamp when the call record was last updated
 * @member {String} updated_at_dts
 */
ConversationPbxCall.prototype['updated_at_dts'] = undefined;






export default ConversationPbxCall;

