/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.UltraCartRestApiV2) {
      root.UltraCartRestApiV2 = {};
    }
    root.UltraCartRestApiV2.CustomerSoftwareEntitlement = factory(root.UltraCartRestApiV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The CustomerSoftwareEntitlement model module.
   * @module com.ultracart.admin.v2.models/CustomerSoftwareEntitlement
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>CustomerSoftwareEntitlement</code>.
   * @alias module:com.ultracart.admin.v2.models/CustomerSoftwareEntitlement
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CustomerSoftwareEntitlement</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ultracart.admin.v2.models/CustomerSoftwareEntitlement} obj Optional instance to populate.
   * @return {module:com.ultracart.admin.v2.models/CustomerSoftwareEntitlement} The populated <code>CustomerSoftwareEntitlement</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('activation_code'))
        obj.activationCode = ApiClient.convertToType(data['activation_code'], 'String');
      if (data.hasOwnProperty('activation_dts'))
        obj.activationDts = ApiClient.convertToType(data['activation_dts'], 'String');
      if (data.hasOwnProperty('customer_software_entitlement_oid'))
        obj.customerSoftwareEntitlementOid = ApiClient.convertToType(data['customer_software_entitlement_oid'], 'Number');
      if (data.hasOwnProperty('expiration_dts'))
        obj.expirationDts = ApiClient.convertToType(data['expiration_dts'], 'String');
      if (data.hasOwnProperty('purchased_via_item_description'))
        obj.purchasedViaItemDescription = ApiClient.convertToType(data['purchased_via_item_description'], 'String');
      if (data.hasOwnProperty('purchased_via_item_id'))
        obj.purchasedViaItemId = ApiClient.convertToType(data['purchased_via_item_id'], 'String');
      if (data.hasOwnProperty('purchased_via_order_id'))
        obj.purchasedViaOrderId = ApiClient.convertToType(data['purchased_via_order_id'], 'String');
      if (data.hasOwnProperty('software_sku'))
        obj.softwareSku = ApiClient.convertToType(data['software_sku'], 'String');
    }
    return obj;
  }

  /**
   * Activation Code Associated with the software
   * @member {String} activationCode
   */
  exports.prototype.activationCode = undefined;

  /**
   * Date/time when the activation code was created
   * @member {String} activationDts
   */
  exports.prototype.activationDts = undefined;

  /**
   * Customer profile software entitlement object identifier
   * @member {Number} customerSoftwareEntitlementOid
   */
  exports.prototype.customerSoftwareEntitlementOid = undefined;

  /**
   * Date/time when the activation code will expire
   * @member {String} expirationDts
   */
  exports.prototype.expirationDts = undefined;

  /**
   * Item description used to purchase this software.
   * @member {String} purchasedViaItemDescription
   */
  exports.prototype.purchasedViaItemDescription = undefined;

  /**
   * Item ID used to purchase this software.
   * @member {String} purchasedViaItemId
   */
  exports.prototype.purchasedViaItemId = undefined;

  /**
   * Order ID used to purchase this software.
   * @member {String} purchasedViaOrderId
   */
  exports.prototype.purchasedViaOrderId = undefined;

  /**
   * SKU of the software
   * @member {String} softwareSku
   */
  exports.prototype.softwareSku = undefined;

  return exports;

}));
