/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ultracart.admin.v2.models/EmailListSegmentUsedBy'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EmailListSegmentUsedBy'));
  } else {
    // Browser globals (root is window)
    if (!root.UltraCartRestApiV2) {
      root.UltraCartRestApiV2 = {};
    }
    root.UltraCartRestApiV2.EmailList = factory(root.UltraCartRestApiV2.ApiClient, root.UltraCartRestApiV2.EmailListSegmentUsedBy);
  }
}(this, function(ApiClient, EmailListSegmentUsedBy) {
  'use strict';

  /**
   * The EmailList model module.
   * @module com.ultracart.admin.v2.models/EmailList
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>EmailList</code>.
   * @alias module:com.ultracart.admin.v2.models/EmailList
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>EmailList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ultracart.admin.v2.models/EmailList} obj Optional instance to populate.
   * @return {module:com.ultracart.admin.v2.models/EmailList} The populated <code>EmailList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('allow_csv_download'))
        obj.allowCsvDownload = ApiClient.convertToType(data['allow_csv_download'], 'Boolean');
      if (data.hasOwnProperty('created_dts'))
        obj.createdDts = ApiClient.convertToType(data['created_dts'], 'String');
      if (data.hasOwnProperty('deleted'))
        obj.deleted = ApiClient.convertToType(data['deleted'], 'Boolean');
      if (data.hasOwnProperty('email_list_uuid'))
        obj.emailListUuid = ApiClient.convertToType(data['email_list_uuid'], 'String');
      if (data.hasOwnProperty('member_count'))
        obj.memberCount = ApiClient.convertToType(data['member_count'], 'Number');
      if (data.hasOwnProperty('merchant_id'))
        obj.merchantId = ApiClient.convertToType(data['merchant_id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('public_description'))
        obj.publicDescription = ApiClient.convertToType(data['public_description'], 'String');
      if (data.hasOwnProperty('public_list'))
        obj.publicList = ApiClient.convertToType(data['public_list'], 'Boolean');
      if (data.hasOwnProperty('storefront_oid'))
        obj.storefrontOid = ApiClient.convertToType(data['storefront_oid'], 'Number');
      if (data.hasOwnProperty('used_by'))
        obj.usedBy = ApiClient.convertToType(data['used_by'], [EmailListSegmentUsedBy]);
    }
    return obj;
  }

  /**
   * True if the current user has the rights to download this list.
   * @member {Boolean} allowCsvDownload
   */
  exports.prototype.allowCsvDownload = undefined;

  /**
   * Created date
   * @member {String} createdDts
   */
  exports.prototype.createdDts = undefined;

  /**
   * True if this campaign was deleted
   * @member {Boolean} deleted
   */
  exports.prototype.deleted = undefined;

  /**
   * Email list UUID
   * @member {String} emailListUuid
   */
  exports.prototype.emailListUuid = undefined;

  /**
   * Count of members in this list
   * @member {Number} memberCount
   */
  exports.prototype.memberCount = undefined;

  /**
   * Merchant ID
   * @member {String} merchantId
   */
  exports.prototype.merchantId = undefined;

  /**
   * Name of email list
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * Description of list shown to customer.
   * @member {String} publicDescription
   */
  exports.prototype.publicDescription = undefined;

  /**
   * True if this list is public
   * @member {Boolean} publicList
   */
  exports.prototype.publicList = undefined;

  /**
   * Storefront oid
   * @member {Number} storefrontOid
   */
  exports.prototype.storefrontOid = undefined;

  /**
   * Details on the flows or campaigns that use this list.
   * @member {Array.<module:com.ultracart.admin.v2.models/EmailListSegmentUsedBy>} usedBy
   */
  exports.prototype.usedBy = undefined;

  return exports;

}));
