/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FraudRuleStorefrontFilter model module.
 * @module com.ultracart.admin.v2.models/FraudRuleStorefrontFilter
 * @version 4.1.128
 */
class FraudRuleStorefrontFilter {
    /**
     * Constructs a new <code>FraudRuleStorefrontFilter</code>.
     * @alias module:com.ultracart.admin.v2.models/FraudRuleStorefrontFilter
     */
    constructor() { 
        
        FraudRuleStorefrontFilter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FraudRuleStorefrontFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/FraudRuleStorefrontFilter} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/FraudRuleStorefrontFilter} The populated <code>FraudRuleStorefrontFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FraudRuleStorefrontFilter();

            if (data.hasOwnProperty('screen_branding_theme_code')) {
                obj['screen_branding_theme_code'] = ApiClient.convertToType(data['screen_branding_theme_code'], 'String');
            }
            if (data.hasOwnProperty('storefront_host_name')) {
                obj['storefront_host_name'] = ApiClient.convertToType(data['storefront_host_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Screen branding theme code associated with this storefront (legacy checkouts)
 * @member {String} screen_branding_theme_code
 */
FraudRuleStorefrontFilter.prototype['screen_branding_theme_code'] = undefined;

/**
 * StoreFront Host Name
 * @member {String} storefront_host_name
 */
FraudRuleStorefrontFilter.prototype['storefront_host_name'] = undefined;






export default FraudRuleStorefrontFilter;

