/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FraudDeclineEmailRequest model module.
 * @module com.ultracart.admin.v2.models/FraudDeclineEmailRequest
 * @version 4.1.105
 */
class FraudDeclineEmailRequest {
    /**
     * Constructs a new <code>FraudDeclineEmailRequest</code>.
     * @alias module:com.ultracart.admin.v2.models/FraudDeclineEmailRequest
     */
    constructor() { 
        
        FraudDeclineEmailRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FraudDeclineEmailRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/FraudDeclineEmailRequest} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/FraudDeclineEmailRequest} The populated <code>FraudDeclineEmailRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FraudDeclineEmailRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }


}

/**
 * email to decline during checkout fraud review
 * @member {String} email
 */
FraudDeclineEmailRequest.prototype['email'] = undefined;






export default FraudDeclineEmailRequest;

