/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ultracart.admin.v2.models/ItemPricingTier'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ItemPricingTier'));
  } else {
    // Browser globals (root is window)
    if (!root.UltraCartRestApiV2) {
      root.UltraCartRestApiV2 = {};
    }
    root.UltraCartRestApiV2.ItemPricing = factory(root.UltraCartRestApiV2.ApiClient, root.UltraCartRestApiV2.ItemPricingTier);
  }
}(this, function(ApiClient, ItemPricingTier) {
  'use strict';

  /**
   * The ItemPricing model module.
   * @module com.ultracart.admin.v2.models/ItemPricing
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>ItemPricing</code>.
   * @alias module:com.ultracart.admin.v2.models/ItemPricing
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ItemPricing</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ultracart.admin.v2.models/ItemPricing} obj Optional instance to populate.
   * @return {module:com.ultracart.admin.v2.models/ItemPricing} The populated <code>ItemPricing</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('allow_arbitrary_cost'))
        obj.allowArbitraryCost = ApiClient.convertToType(data['allow_arbitrary_cost'], 'Boolean');
      if (data.hasOwnProperty('arbitrary_cost_velocity_code'))
        obj.arbitraryCostVelocityCode = ApiClient.convertToType(data['arbitrary_cost_velocity_code'], 'String');
      if (data.hasOwnProperty('auto_order_cost'))
        obj.autoOrderCost = ApiClient.convertToType(data['auto_order_cost'], 'Number');
      if (data.hasOwnProperty('automatic_pricing_tier_name'))
        obj.automaticPricingTierName = ApiClient.convertToType(data['automatic_pricing_tier_name'], 'String');
      if (data.hasOwnProperty('automatic_pricing_tier_oid'))
        obj.automaticPricingTierOid = ApiClient.convertToType(data['automatic_pricing_tier_oid'], 'Number');
      if (data.hasOwnProperty('cogs'))
        obj.cogs = ApiClient.convertToType(data['cogs'], 'Number');
      if (data.hasOwnProperty('cost'))
        obj.cost = ApiClient.convertToType(data['cost'], 'Number');
      if (data.hasOwnProperty('currency_code'))
        obj.currencyCode = ApiClient.convertToType(data['currency_code'], 'String');
      if (data.hasOwnProperty('manufacturer_suggested_retail_price'))
        obj.manufacturerSuggestedRetailPrice = ApiClient.convertToType(data['manufacturer_suggested_retail_price'], 'Number');
      if (data.hasOwnProperty('maximum_arbitrary_cost'))
        obj.maximumArbitraryCost = ApiClient.convertToType(data['maximum_arbitrary_cost'], 'Number');
      if (data.hasOwnProperty('minimum_advertised_price'))
        obj.minimumAdvertisedPrice = ApiClient.convertToType(data['minimum_advertised_price'], 'Number');
      if (data.hasOwnProperty('minimum_arbitrary_cost'))
        obj.minimumArbitraryCost = ApiClient.convertToType(data['minimum_arbitrary_cost'], 'Number');
      if (data.hasOwnProperty('mix_and_match_group'))
        obj.mixAndMatchGroup = ApiClient.convertToType(data['mix_and_match_group'], 'String');
      if (data.hasOwnProperty('mix_and_match_group_oid'))
        obj.mixAndMatchGroupOid = ApiClient.convertToType(data['mix_and_match_group_oid'], 'Number');
      if (data.hasOwnProperty('sale_cost'))
        obj.saleCost = ApiClient.convertToType(data['sale_cost'], 'Number');
      if (data.hasOwnProperty('sale_end'))
        obj.saleEnd = ApiClient.convertToType(data['sale_end'], 'String');
      if (data.hasOwnProperty('sale_start'))
        obj.saleStart = ApiClient.convertToType(data['sale_start'], 'String');
      if (data.hasOwnProperty('tiers'))
        obj.tiers = ApiClient.convertToType(data['tiers'], [ItemPricingTier]);
    }
    return obj;
  }

  /**
   * Allow arbitrary cost
   * @member {Boolean} allowArbitraryCost
   */
  exports.prototype.allowArbitraryCost = undefined;

  /**
   * Arbitrary cost velocity code
   * @member {String} arbitraryCostVelocityCode
   */
  exports.prototype.arbitraryCostVelocityCode = undefined;

  /**
   * Cost if customer selects to receive item on auto order.  Set to zero to delete.
   * @member {Number} autoOrderCost
   */
  exports.prototype.autoOrderCost = undefined;

  /**
   * Automatic pricing tier name
   * @member {String} automaticPricingTierName
   */
  exports.prototype.automaticPricingTierName = undefined;

  /**
   * Automatic pricing tier object identifier
   * @member {Number} automaticPricingTierOid
   */
  exports.prototype.automaticPricingTierOid = undefined;

  /**
   * Cost of goods sold
   * @member {Number} cogs
   */
  exports.prototype.cogs = undefined;

  /**
   * Cost
   * @member {Number} cost
   */
  exports.prototype.cost = undefined;

  /**
   * Currency code
   * @member {String} currencyCode
   */
  exports.prototype.currencyCode = undefined;

  /**
   * Manufacturer suggested retail price
   * @member {Number} manufacturerSuggestedRetailPrice
   */
  exports.prototype.manufacturerSuggestedRetailPrice = undefined;

  /**
   * Maximum arbitrary cost
   * @member {Number} maximumArbitraryCost
   */
  exports.prototype.maximumArbitraryCost = undefined;

  /**
   * Minimum advertised price
   * @member {Number} minimumAdvertisedPrice
   */
  exports.prototype.minimumAdvertisedPrice = undefined;

  /**
   * Minimum arbitrary cost
   * @member {Number} minimumArbitraryCost
   */
  exports.prototype.minimumArbitraryCost = undefined;

  /**
   * Mix and match group
   * @member {String} mixAndMatchGroup
   */
  exports.prototype.mixAndMatchGroup = undefined;

  /**
   * Mix and match group object identifier
   * @member {Number} mixAndMatchGroupOid
   */
  exports.prototype.mixAndMatchGroupOid = undefined;

  /**
   * Sale cost
   * @member {Number} saleCost
   */
  exports.prototype.saleCost = undefined;

  /**
   * Sale end
   * @member {String} saleEnd
   */
  exports.prototype.saleEnd = undefined;

  /**
   * Sale start
   * @member {String} saleStart
   */
  exports.prototype.saleStart = undefined;

  /**
   * Tiers
   * @member {Array.<module:com.ultracart.admin.v2.models/ItemPricingTier>} tiers
   */
  exports.prototype.tiers = undefined;

  return exports;

}));
