/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ultracart.admin.v2.models/OrderItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderItem'));
  } else {
    // Browser globals (root is window)
    if (!root.UltraCartRestApiV2) {
      root.UltraCartRestApiV2 = {};
    }
    root.UltraCartRestApiV2.OrderAddItemsAndReleaseRequest = factory(root.UltraCartRestApiV2.ApiClient, root.UltraCartRestApiV2.OrderItem);
  }
}(this, function(ApiClient, OrderItem) {
  'use strict';

  /**
   * The OrderAddItemsAndReleaseRequest model module.
   * @module com.ultracart.admin.v2.models/OrderAddItemsAndReleaseRequest
   * @version 3.11.63
   */

  /**
   * Constructs a new <code>OrderAddItemsAndReleaseRequest</code>.
   * @alias module:com.ultracart.admin.v2.models/OrderAddItemsAndReleaseRequest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>OrderAddItemsAndReleaseRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ultracart.admin.v2.models/OrderAddItemsAndReleaseRequest} obj Optional instance to populate.
   * @return {module:com.ultracart.admin.v2.models/OrderAddItemsAndReleaseRequest} The populated <code>OrderAddItemsAndReleaseRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [OrderItem]);
    }
    return obj;
  }

  /**
   * Items to add to the order.  Must have at least the item id and quantity specified.  These will be FREE items on the order since we are post payment on this method.
   * @member {Array.<module:com.ultracart.admin.v2.models/OrderItem>} items
   */
  exports.prototype.items = undefined;

  return exports;

}));
