/*
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.ultracart.admin.v2.models/PaymentsConfigurationRestrictions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PaymentsConfigurationRestrictions'));
  } else {
    // Browser globals (root is window)
    if (!root.UltraCartRestApiV2) {
      root.UltraCartRestApiV2 = {};
    }
    root.UltraCartRestApiV2.PaymentsConfigurationAffirm = factory(root.UltraCartRestApiV2.ApiClient, root.UltraCartRestApiV2.PaymentsConfigurationRestrictions);
  }
}(this, function(ApiClient, PaymentsConfigurationRestrictions) {
  'use strict';

  /**
   * The PaymentsConfigurationAffirm model module.
   * @module com.ultracart.admin.v2.models/PaymentsConfigurationAffirm
   * @version 3.4.5
   */

  /**
   * Constructs a new <code>PaymentsConfigurationAffirm</code>.
   * @alias module:com.ultracart.admin.v2.models/PaymentsConfigurationAffirm
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PaymentsConfigurationAffirm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.ultracart.admin.v2.models/PaymentsConfigurationAffirm} obj Optional instance to populate.
   * @return {module:com.ultracart.admin.v2.models/PaymentsConfigurationAffirm} The populated <code>PaymentsConfigurationAffirm</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('acceptAffirm'))
        obj.acceptAffirm = ApiClient.convertToType(data['acceptAffirm'], 'Boolean');
      if (data.hasOwnProperty('affirmAccountingCode'))
        obj.affirmAccountingCode = ApiClient.convertToType(data['affirmAccountingCode'], 'String');
      if (data.hasOwnProperty('affirmDepositToAccount'))
        obj.affirmDepositToAccount = ApiClient.convertToType(data['affirmDepositToAccount'], 'String');
      if (data.hasOwnProperty('affirmEnvironment'))
        obj.affirmEnvironment = ApiClient.convertToType(data['affirmEnvironment'], 'String');
      if (data.hasOwnProperty('affirmFinancialProductKey'))
        obj.affirmFinancialProductKey = ApiClient.convertToType(data['affirmFinancialProductKey'], 'String');
      if (data.hasOwnProperty('affirmPrivateApiKey'))
        obj.affirmPrivateApiKey = ApiClient.convertToType(data['affirmPrivateApiKey'], 'String');
      if (data.hasOwnProperty('affirmPublicApiKey'))
        obj.affirmPublicApiKey = ApiClient.convertToType(data['affirmPublicApiKey'], 'String');
      if (data.hasOwnProperty('restrictions'))
        obj.restrictions = PaymentsConfigurationRestrictions.constructFromObject(data['restrictions']);
    }
    return obj;
  }

  /**
   * @member {Boolean} acceptAffirm
   */
  exports.prototype.acceptAffirm = undefined;

  /**
   * @member {String} affirmAccountingCode
   */
  exports.prototype.affirmAccountingCode = undefined;

  /**
   * @member {String} affirmDepositToAccount
   */
  exports.prototype.affirmDepositToAccount = undefined;

  /**
   * @member {String} affirmEnvironment
   */
  exports.prototype.affirmEnvironment = undefined;

  /**
   * @member {String} affirmFinancialProductKey
   */
  exports.prototype.affirmFinancialProductKey = undefined;

  /**
   * @member {String} affirmPrivateApiKey
   */
  exports.prototype.affirmPrivateApiKey = undefined;

  /**
   * @member {String} affirmPublicApiKey
   */
  exports.prototype.affirmPublicApiKey = undefined;

  /**
   * @member {module:com.ultracart.admin.v2.models/PaymentsConfigurationRestrictions} restrictions
   */
  exports.prototype.restrictions = undefined;

  return exports;

}));
