/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportDataSetColumn from './ReportDataSetColumn';

/**
 * The ReportDataSetRow model module.
 * @module com.ultracart.admin.v2.models/ReportDataSetRow
 * @version 4.1.40
 */
class ReportDataSetRow {
    /**
     * Constructs a new <code>ReportDataSetRow</code>.
     * @alias module:com.ultracart.admin.v2.models/ReportDataSetRow
     */
    constructor() { 
        
        ReportDataSetRow.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportDataSetRow</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/ReportDataSetRow} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/ReportDataSetRow} The populated <code>ReportDataSetRow</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportDataSetRow();

            if (data.hasOwnProperty('c')) {
                obj['c'] = ApiClient.convertToType(data['c'], [ReportDataSetColumn]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:com.ultracart.admin.v2.models/ReportDataSetColumn>} c
 */
ReportDataSetRow.prototype['c'] = undefined;






export default ReportDataSetRow;

