/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SfvbPageSettingsRequest model module.
 * @module com.ultracart.admin.v2.models/SfvbPageSettingsRequest
 * @version 4.1.173
 */
class SfvbPageSettingsRequest {
    /**
     * Constructs a new <code>SfvbPageSettingsRequest</code>.
     * @alias module:com.ultracart.admin.v2.models/SfvbPageSettingsRequest
     */
    constructor() { 
        
        SfvbPageSettingsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SfvbPageSettingsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/SfvbPageSettingsRequest} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/SfvbPageSettingsRequest} The populated <code>SfvbPageSettingsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SfvbPageSettingsRequest();

            if (data.hasOwnProperty('blog_post_template')) {
                obj['blog_post_template'] = ApiClient.convertToType(data['blog_post_template'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('exclude_from_sitemap')) {
                obj['exclude_from_sitemap'] = ApiClient.convertToType(data['exclude_from_sitemap'], 'Boolean');
            }
            if (data.hasOwnProperty('group_template')) {
                obj['group_template'] = ApiClient.convertToType(data['group_template'], 'String');
            }
            if (data.hasOwnProperty('item_template')) {
                obj['item_template'] = ApiClient.convertToType(data['item_template'], 'String');
            }
            if (data.hasOwnProperty('items_per_page')) {
                obj['items_per_page'] = ApiClient.convertToType(data['items_per_page'], 'Number');
            }
            if (data.hasOwnProperty('page_type')) {
                obj['page_type'] = ApiClient.convertToType(data['page_type'], 'String');
            }
            if (data.hasOwnProperty('review_template')) {
                obj['review_template'] = ApiClient.convertToType(data['review_template'], 'String');
            }
            if (data.hasOwnProperty('sort_order')) {
                obj['sort_order'] = ApiClient.convertToType(data['sort_order'], 'Number');
            }
            if (data.hasOwnProperty('sort_order_child_groups')) {
                obj['sort_order_child_groups'] = ApiClient.convertToType(data['sort_order_child_groups'], 'String');
            }
            if (data.hasOwnProperty('sort_order_child_items')) {
                obj['sort_order_child_items'] = ApiClient.convertToType(data['sort_order_child_items'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'Boolean');
            }
            if (data.hasOwnProperty('visible_dts')) {
                obj['visible_dts'] = ApiClient.convertToType(data['visible_dts'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Template that renders the blog posts under this page.
 * @member {String} blog_post_template
 */
SfvbPageSettingsRequest.prototype['blog_post_template'] = undefined;

/**
 * The page description.  Null or empty clears it.
 * @member {String} description
 */
SfvbPageSettingsRequest.prototype['description'] = undefined;

/**
 * Leave the page out of the sitemap and mark it noindex.
 * @member {Boolean} exclude_from_sitemap
 */
SfvbPageSettingsRequest.prototype['exclude_from_sitemap'] = undefined;

/**
 * Template that renders the page, a name from the template list.
 * @member {String} group_template
 */
SfvbPageSettingsRequest.prototype['group_template'] = undefined;

/**
 * Template that renders the item pages under this page.
 * @member {String} item_template
 */
SfvbPageSettingsRequest.prototype['item_template'] = undefined;

/**
 * Items per page on a template that paginates.  Null returns to the template's default.
 * @member {Number} items_per_page
 */
SfvbPageSettingsRequest.prototype['items_per_page'] = undefined;

/**
 * S for a static page, D for a dynamic one.
 * @member {String} page_type
 */
SfvbPageSettingsRequest.prototype['page_type'] = undefined;

/**
 * Template that renders the item review pages under this page.
 * @member {String} review_template
 */
SfvbPageSettingsRequest.prototype['review_template'] = undefined;

/**
 * Position among its siblings when the parent sorts child pages by a custom order.  Null clears it.
 * @member {Number} sort_order
 */
SfvbPageSettingsRequest.prototype['sort_order'] = undefined;

/**
 * How the pages under this one are ordered.  TA or TD by title, DA or DD by description, C custom.
 * @member {String} sort_order_child_groups
 */
SfvbPageSettingsRequest.prototype['sort_order_child_groups'] = undefined;

/**
 * How the page's items are ordered.  IA or ID by item id, DA or DD by description, SA or SD by manufacturer SKU, PA or PD by price, RA or RD by review, NA or ND by inventory, C custom.
 * @member {String} sort_order_child_items
 */
SfvbPageSettingsRequest.prototype['sort_order_child_items'] = undefined;

/**
 * The page title.
 * @member {String} title
 */
SfvbPageSettingsRequest.prototype['title'] = undefined;

/**
 * False hides the page, so it answers 404 to shoppers.  The root page cannot be hidden.
 * @member {Boolean} visible
 */
SfvbPageSettingsRequest.prototype['visible'] = undefined;

/**
 * Keep the page hidden until this time (ISO 8601).  Null or empty clears it.
 * @member {String} visible_dts
 */
SfvbPageSettingsRequest.prototype['visible_dts'] = undefined;






export default SfvbPageSettingsRequest;

