/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SfvbPageBlogPostsRequest model module.
 * @module com.ultracart.admin.v2.models/SfvbPageBlogPostsRequest
 * @version 4.1.169
 */
class SfvbPageBlogPostsRequest {
    /**
     * Constructs a new <code>SfvbPageBlogPostsRequest</code>.
     * @alias module:com.ultracart.admin.v2.models/SfvbPageBlogPostsRequest
     */
    constructor() { 
        
        SfvbPageBlogPostsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SfvbPageBlogPostsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/SfvbPageBlogPostsRequest} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/SfvbPageBlogPostsRequest} The populated <code>SfvbPageBlogPostsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SfvbPageBlogPostsRequest();

            if (data.hasOwnProperty('blog_post_oids')) {
                obj['blog_post_oids'] = ApiClient.convertToType(data['blog_post_oids'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * Blog post oids from the blog post list, at most 500.
 * @member {Array.<Number>} blog_post_oids
 */
SfvbPageBlogPostsRequest.prototype['blog_post_oids'] = undefined;






export default SfvbPageBlogPostsRequest;

