/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SfvbUpsellTowerData model module.
 * @module com.ultracart.admin.v2.models/SfvbUpsellTowerData
 * @version 4.1.174
 */
class SfvbUpsellTowerData {
    /**
     * Constructs a new <code>SfvbUpsellTowerData</code>.
     * @alias module:com.ultracart.admin.v2.models/SfvbUpsellTowerData
     */
    constructor() { 
        
        SfvbUpsellTowerData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SfvbUpsellTowerData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/SfvbUpsellTowerData} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/SfvbUpsellTowerData} The populated <code>SfvbUpsellTowerData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SfvbUpsellTowerData();

            if (data.hasOwnProperty('ages')) {
                obj['ages'] = ApiClient.convertToType(data['ages'], ['String']);
            }
            if (data.hasOwnProperty('genders')) {
                obj['genders'] = ApiClient.convertToType(data['genders'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Age bands the path is shown to.  18-20, 21-24, 25-34, 35-44, 45-54, 55-64, 65+ or Unknown.
 * @member {Array.<String>} ages
 */
SfvbUpsellTowerData.prototype['ages'] = undefined;

/**
 * Genders the path is shown to.  Male, Female or Unknown.
 * @member {Array.<String>} genders
 */
SfvbUpsellTowerData.prototype['genders'] = undefined;






export default SfvbUpsellTowerData;

