/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SfvbSiteAttribute model module.
 * @module com.ultracart.admin.v2.models/SfvbSiteAttribute
 * @version 4.1.168
 */
class SfvbSiteAttribute {
    /**
     * Constructs a new <code>SfvbSiteAttribute</code>.
     * @alias module:com.ultracart.admin.v2.models/SfvbSiteAttribute
     */
    constructor() { 
        
        SfvbSiteAttribute.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SfvbSiteAttribute</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/SfvbSiteAttribute} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/SfvbSiteAttribute} The populated <code>SfvbSiteAttribute</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SfvbSiteAttribute();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('undeclared')) {
                obj['undeclared'] = ApiClient.convertToType(data['undeclared'], 'Boolean');
            }
            if (data.hasOwnProperty('used_by')) {
                obj['used_by'] = ApiClient.convertToType(data['used_by'], 'String');
            }
            if (data.hasOwnProperty('used_by_current_theme')) {
                obj['used_by_current_theme'] = ApiClient.convertToType(data['used_by_current_theme'], 'Boolean');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('writable')) {
                obj['writable'] = ApiClient.convertToType(data['writable'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Attribute name, as a template's site attribute declaration spells it.  Compare case insensitively.  This is the value siteAttributeName refers to and the name $site.attr takes.
 * @member {String} name
 */
SfvbSiteAttribute.prototype['name'] = undefined;

/**
 * What kind of attribute this is, taken from the template that declares it rather than from the stored row.  orphan means no template declares it.  reserved covers the settings the StoreFronts General screen owns.
 * @member {module:com.ultracart.admin.v2.models/SfvbSiteAttribute.TypeEnum} type
 */
SfvbSiteAttribute.prototype['type'] = undefined;

/**
 * True when no template declares this name and it is not a reserved setting.  A template can still read it with $site.attr, so this is not proof it is unused, but a name you did not mean to create is most likely a misspelling.
 * @member {Boolean} undeclared
 */
SfvbSiteAttribute.prototype['undeclared'] = undefined;

/**
 * The other themes that declare this attribute, when the active theme does not.
 * @member {String} used_by
 */
SfvbSiteAttribute.prototype['used_by'] = undefined;

/**
 * True when a template in the active theme declares this attribute.
 * @member {Boolean} used_by_current_theme
 */
SfvbSiteAttribute.prototype['used_by_current_theme'] = undefined;

/**
 * The stored value, or the template default when nothing has set it.
 * @member {String} value
 */
SfvbSiteAttribute.prototype['value'] = undefined;

/**
 * True when this API will change the value.  List, video list, mailing list and item set values are structured documents and must be edited in the store admin.  Of the reserved settings only the title, the SEO description and keywords and the social account names are writable here.
 * @member {Boolean} writable
 */
SfvbSiteAttribute.prototype['writable'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
SfvbSiteAttribute['TypeEnum'] = {

    /**
     * value: "string"
     * @const
     */
    "string": "string",

    /**
     * value: "multiline"
     * @const
     */
    "multiline": "multiline",

    /**
     * value: "html"
     * @const
     */
    "html": "html",

    /**
     * value: "color"
     * @const
     */
    "color": "color",

    /**
     * value: "rgba"
     * @const
     */
    "rgba": "rgba",

    /**
     * value: "boolean"
     * @const
     */
    "boolean": "boolean",

    /**
     * value: "integer"
     * @const
     */
    "integer": "integer",

    /**
     * value: "orphan"
     * @const
     */
    "orphan": "orphan",

    /**
     * value: "reserved"
     * @const
     */
    "reserved": "reserved",

    /**
     * value: "simplelist"
     * @const
     */
    "simplelist": "simplelist",

    /**
     * value: "definitionlist"
     * @const
     */
    "definitionlist": "definitionlist",

    /**
     * value: "videolist"
     * @const
     */
    "videolist": "videolist",

    /**
     * value: "mailinglist"
     * @const
     */
    "mailinglist": "mailinglist",

    /**
     * value: "itemset"
     * @const
     */
    "itemset": "itemset"
};



export default SfvbSiteAttribute;

