/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SfvbTemplate from './SfvbTemplate';

/**
 * The SfvbTemplatesResponse model module.
 * @module com.ultracart.admin.v2.models/SfvbTemplatesResponse
 * @version 4.1.169
 */
class SfvbTemplatesResponse {
    /**
     * Constructs a new <code>SfvbTemplatesResponse</code>.
     * @alias module:com.ultracart.admin.v2.models/SfvbTemplatesResponse
     */
    constructor() { 
        
        SfvbTemplatesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SfvbTemplatesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/SfvbTemplatesResponse} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/SfvbTemplatesResponse} The populated <code>SfvbTemplatesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SfvbTemplatesResponse();

            if (data.hasOwnProperty('templates')) {
                obj['templates'] = ApiClient.convertToType(data['templates'], [SfvbTemplate]);
            }
            if (data.hasOwnProperty('theme_oid')) {
                obj['theme_oid'] = ApiClient.convertToType(data['theme_oid'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Templates sorted by name.
 * @member {Array.<module:com.ultracart.admin.v2.models/SfvbTemplate>} templates
 */
SfvbTemplatesResponse.prototype['templates'] = undefined;

/**
 * The active theme the templates were read from.
 * @member {Number} theme_oid
 */
SfvbTemplatesResponse.prototype['theme_oid'] = undefined;






export default SfvbTemplatesResponse;

