/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SfvbLibraryFacet model module.
 * @module com.ultracart.admin.v2.models/SfvbLibraryFacet
 * @version 4.1.146
 */
class SfvbLibraryFacet {
    /**
     * Constructs a new <code>SfvbLibraryFacet</code>.
     * @alias module:com.ultracart.admin.v2.models/SfvbLibraryFacet
     */
    constructor() { 
        
        SfvbLibraryFacet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SfvbLibraryFacet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.ultracart.admin.v2.models/SfvbLibraryFacet} obj Optional instance to populate.
     * @return {module:com.ultracart.admin.v2.models/SfvbLibraryFacet} The populated <code>SfvbLibraryFacet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SfvbLibraryFacet();

            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Human readable facet name.
 * @member {String} display_name
 */
SfvbLibraryFacet.prototype['display_name'] = undefined;

/**
 * Facet key.  Pass a chosen option back as facet_{name}={option}.
 * @member {String} name
 */
SfvbLibraryFacet.prototype['name'] = undefined;

/**
 * Available values for this facet.
 * @member {Array.<String>} options
 */
SfvbLibraryFacet.prototype['options'] = undefined;






export default SfvbLibraryFacet;

