/**
 * UltraCart Rest API V2
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../com.ultracart.admin.v2.models/ErrorResponse';
import TaxCity from '../com.ultracart.admin.v2.models/TaxCity';
import TaxCountry from '../com.ultracart.admin.v2.models/TaxCountry';
import TaxCounty from '../com.ultracart.admin.v2.models/TaxCounty';
import TaxPostalCode from '../com.ultracart.admin.v2.models/TaxPostalCode';
import TaxProviderActivateResult from '../com.ultracart.admin.v2.models/TaxProviderActivateResult';
import TaxProviderAvalara from '../com.ultracart.admin.v2.models/TaxProviderAvalara';
import TaxProviderAvalaraCompaniesResult from '../com.ultracart.admin.v2.models/TaxProviderAvalaraCompaniesResult';
import TaxProviderSelf from '../com.ultracart.admin.v2.models/TaxProviderSelf';
import TaxProviderSelfCountriesResponse from '../com.ultracart.admin.v2.models/TaxProviderSelfCountriesResponse';
import TaxProviderSelfRegionsResponse from '../com.ultracart.admin.v2.models/TaxProviderSelfRegionsResponse';
import TaxProviderSovos from '../com.ultracart.admin.v2.models/TaxProviderSovos';
import TaxProviderTaxJar from '../com.ultracart.admin.v2.models/TaxProviderTaxJar';
import TaxProviderTestResult from '../com.ultracart.admin.v2.models/TaxProviderTestResult';
import TaxProviderUltraCart from '../com.ultracart.admin.v2.models/TaxProviderUltraCart';
import TaxProvidersResponse from '../com.ultracart.admin.v2.models/TaxProvidersResponse';
import TaxState from '../com.ultracart.admin.v2.models/TaxState';

/**
* Tax service.
* @module com.ultracart.admin.v2/TaxApi
* @version 4.0.65-RC
*/
export default class TaxApi {

    /**
    * Constructs a new TaxApi. 
    * @alias module:com.ultracart.admin.v2/TaxApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteTaxProviderSelfCity operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfCityCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a Self tax provider city
     * Deletes a Self tax provider city. 
     * @param {String} city The city being deleted.
     * @param {module:com.ultracart.admin.v2.models/TaxCity} tax_city tax city to be deleted
     * @param {module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfCityCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTaxProviderSelfCity(city, tax_city, callback) {
      let postBody = tax_city;
      // verify the required parameter 'city' is set
      if (city === undefined || city === null) {
        throw new Error("Missing the required parameter 'city' when calling deleteTaxProviderSelfCity");
      }
      // verify the required parameter 'tax_city' is set
      if (tax_city === undefined || tax_city === null) {
        throw new Error("Missing the required parameter 'tax_city' when calling deleteTaxProviderSelfCity");
      }

      let pathParams = {
        'city': city
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/tax/providers/self/city/{city}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTaxProviderSelfCountry operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfCountryCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a Self tax provider country
     * Deletes a Self tax provider country. 
     * @param {String} countryCode The country code being deleted.
     * @param {module:com.ultracart.admin.v2.models/TaxCountry} tax_country tax country to be deleted
     * @param {module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfCountryCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTaxProviderSelfCountry(countryCode, tax_country, callback) {
      let postBody = tax_country;
      // verify the required parameter 'countryCode' is set
      if (countryCode === undefined || countryCode === null) {
        throw new Error("Missing the required parameter 'countryCode' when calling deleteTaxProviderSelfCountry");
      }
      // verify the required parameter 'tax_country' is set
      if (tax_country === undefined || tax_country === null) {
        throw new Error("Missing the required parameter 'tax_country' when calling deleteTaxProviderSelfCountry");
      }

      let pathParams = {
        'countryCode': countryCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/tax/providers/self/country/{countryCode}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTaxProviderSelfCounty operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfCountyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a Self tax provider county
     * Deletes a Self tax provider county. 
     * @param {String} county The county being deleted.
     * @param {module:com.ultracart.admin.v2.models/TaxCounty} tax_county tax county to be deleted
     * @param {module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfCountyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTaxProviderSelfCounty(county, tax_county, callback) {
      let postBody = tax_county;
      // verify the required parameter 'county' is set
      if (county === undefined || county === null) {
        throw new Error("Missing the required parameter 'county' when calling deleteTaxProviderSelfCounty");
      }
      // verify the required parameter 'tax_county' is set
      if (tax_county === undefined || tax_county === null) {
        throw new Error("Missing the required parameter 'tax_county' when calling deleteTaxProviderSelfCounty");
      }

      let pathParams = {
        'county': county
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/tax/providers/self/county/{county}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTaxProviderSelfPostalCode operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfPostalCodeCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a Self tax provider postalCode
     * Deletes a Self tax provider postalCode. 
     * @param {String} postal_code The postal code being deleted.
     * @param {module:com.ultracart.admin.v2.models/TaxPostalCode} tax_postal_code tax postal code to be deleted
     * @param {module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfPostalCodeCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTaxProviderSelfPostalCode(postal_code, tax_postal_code, callback) {
      let postBody = tax_postal_code;
      // verify the required parameter 'postal_code' is set
      if (postal_code === undefined || postal_code === null) {
        throw new Error("Missing the required parameter 'postal_code' when calling deleteTaxProviderSelfPostalCode");
      }
      // verify the required parameter 'tax_postal_code' is set
      if (tax_postal_code === undefined || tax_postal_code === null) {
        throw new Error("Missing the required parameter 'tax_postal_code' when calling deleteTaxProviderSelfPostalCode");
      }

      let pathParams = {
        'postal_code': postal_code
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/tax/providers/self/postalCode/{postal_code}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTaxProviderSelfState operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfStateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes a Self tax provider state
     * Deletes a Self tax provider state. 
     * @param {String} stateCode The state code being deleted.
     * @param {module:com.ultracart.admin.v2.models/TaxState} tax_state tax state to be deleted
     * @param {module:com.ultracart.admin.v2/TaxApi~deleteTaxProviderSelfStateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteTaxProviderSelfState(stateCode, tax_state, callback) {
      let postBody = tax_state;
      // verify the required parameter 'stateCode' is set
      if (stateCode === undefined || stateCode === null) {
        throw new Error("Missing the required parameter 'stateCode' when calling deleteTaxProviderSelfState");
      }
      // verify the required parameter 'tax_state' is set
      if (tax_state === undefined || tax_state === null) {
        throw new Error("Missing the required parameter 'tax_state' when calling deleteTaxProviderSelfState");
      }

      let pathParams = {
        'stateCode': stateCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/tax/providers/self/state/{stateCode}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderAvalara operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderAvalaraCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderAvalara} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the Avalara tax provider
     * Retrieves the Avalara tax provider. 
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderAvalaraCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderAvalara}
     */
    getTaxProviderAvalara(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderAvalara;
      return this.apiClient.callApi(
        '/tax/providers/avalara', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderAvalaraCompanies operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderAvalaraCompaniesCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderAvalaraCompaniesResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns Avalara Tax companies configured by the merchant
     * Returns Avalara Tax companies configured by the merchant 
     * @param {module:com.ultracart.admin.v2.models/TaxProviderAvalara} tax_provider_avalara TaxProviderAvalara object
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderAvalaraCompaniesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderAvalaraCompaniesResult}
     */
    getTaxProviderAvalaraCompanies(tax_provider_avalara, callback) {
      let postBody = tax_provider_avalara;
      // verify the required parameter 'tax_provider_avalara' is set
      if (tax_provider_avalara === undefined || tax_provider_avalara === null) {
        throw new Error("Missing the required parameter 'tax_provider_avalara' when calling getTaxProviderAvalaraCompanies");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxProviderAvalaraCompaniesResult;
      return this.apiClient.callApi(
        '/tax/providers/avalara/companies', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderAvalaraTest operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderAvalaraTestCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderTestResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Attempts to connect to Avalara and returns back the response
     * Attempts to connect to Avalara and returns back the response. 
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderAvalaraTestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderTestResult}
     */
    getTaxProviderAvalaraTest(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderTestResult;
      return this.apiClient.callApi(
        '/tax/providers/avalara/test', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderSelf operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderSelfCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderSelf} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the Self tax provider
     * Retrieves the Self tax provider. 
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderSelfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderSelf}
     */
    getTaxProviderSelf(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderSelf;
      return this.apiClient.callApi(
        '/tax/providers/self', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderSelfCountries operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderSelfCountriesCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderSelfCountriesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the Self tax provider countries
     * Retrieves the Self tax provider countries. 
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderSelfCountriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderSelfCountriesResponse}
     */
    getTaxProviderSelfCountries(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderSelfCountriesResponse;
      return this.apiClient.callApi(
        '/tax/providers/self/countries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderSelfRegionsByCountryCode operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderSelfRegionsByCountryCodeCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderSelfRegionsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the Self tax provider regions for a given country code
     * Retrieves the Self tax provider regions for a given country code. 
     * @param {String} countryCode The country code regions desired.
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderSelfRegionsByCountryCodeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderSelfRegionsResponse}
     */
    getTaxProviderSelfRegionsByCountryCode(countryCode, callback) {
      let postBody = null;
      // verify the required parameter 'countryCode' is set
      if (countryCode === undefined || countryCode === null) {
        throw new Error("Missing the required parameter 'countryCode' when calling getTaxProviderSelfRegionsByCountryCode");
      }

      let pathParams = {
        'countryCode': countryCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderSelfRegionsResponse;
      return this.apiClient.callApi(
        '/tax/providers/self/regions/{countryCode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderSovos operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderSovosCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderSovos} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the Sovos tax provider
     * Retrieves the Sovos tax provider. 
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderSovosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderSovos}
     */
    getTaxProviderSovos(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderSovos;
      return this.apiClient.callApi(
        '/tax/providers/sovos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderSovosTest operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderSovosTestCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderTestResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Attempts to connect to Sovos and returns back the response
     * Attempts to connect to Sovos and returns back the response. 
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderSovosTestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderTestResult}
     */
    getTaxProviderSovosTest(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderTestResult;
      return this.apiClient.callApi(
        '/tax/providers/sovos/test', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderTaxJar operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderTaxJarCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderTaxJar} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the TaxJar tax provider
     * Retrieves the TaxJar tax provider. 
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderTaxJarCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderTaxJar}
     */
    getTaxProviderTaxJar(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderTaxJar;
      return this.apiClient.callApi(
        '/tax/providers/taxjar', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderTaxJarTest operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderTaxJarTestCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderTestResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Attempts to connect to TaxJar and returns back the response
     * Attempts to connect to TaxJar and returns back the response. 
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderTaxJarTestCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderTestResult}
     */
    getTaxProviderTaxJarTest(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderTestResult;
      return this.apiClient.callApi(
        '/tax/providers/taxjar/test', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviderUltraCart operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProviderUltraCartCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderUltraCart} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve the UltraCart tax provider
     * Retrieves the UltraCart tax provider. 
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProviderUltraCartCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderUltraCart}
     */
    getTaxProviderUltraCart(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderUltraCart;
      return this.apiClient.callApi(
        '/tax/providers/ultracart', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getTaxProviders operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~getTaxProvidersCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProvidersResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve tax methods
     * Retrieves tax methods for this account. 
     * @param {Object} opts Optional parameters
     * @param {Number} opts._limit The maximum number of records to return on this one API call. (Max 200) (default to 100)
     * @param {Number} opts._offset Pagination of the record set.  Offset is a zero based index. (default to 0)
     * @param {String} opts._expand The object expansion to perform on the result.  See documentation for examples
     * @param {module:com.ultracart.admin.v2/TaxApi~getTaxProvidersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProvidersResponse}
     */
    getTaxProviders(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        '_limit': opts['_limit'],
        '_offset': opts['_offset'],
        '_expand': opts['_expand']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProvidersResponse;
      return this.apiClient.callApi(
        '/tax/providers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the setActiveTaxProvider operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~setActiveTaxProviderCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderActivateResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Toggle a tax provider to active
     * Toggle a tax provider to active. 
     * @param {String} providerName The tax provider to set active.
     * @param {module:com.ultracart.admin.v2/TaxApi~setActiveTaxProviderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderActivateResult}
     */
    setActiveTaxProvider(providerName, callback) {
      let postBody = null;
      // verify the required parameter 'providerName' is set
      if (providerName === undefined || providerName === null) {
        throw new Error("Missing the required parameter 'providerName' when calling setActiveTaxProvider");
      }

      let pathParams = {
        'providerName': providerName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TaxProviderActivateResult;
      return this.apiClient.callApi(
        '/tax/providers/setActive/{providerName}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderAvalara operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderAvalaraCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderAvalara} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the Avalara tax provider
     * Update the Avalara tax provider. 
     * @param {module:com.ultracart.admin.v2.models/TaxProviderAvalara} tax_provider_avalara TaxProviderAvalara object
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderAvalaraCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderAvalara}
     */
    updateTaxProviderAvalara(tax_provider_avalara, callback) {
      let postBody = tax_provider_avalara;
      // verify the required parameter 'tax_provider_avalara' is set
      if (tax_provider_avalara === undefined || tax_provider_avalara === null) {
        throw new Error("Missing the required parameter 'tax_provider_avalara' when calling updateTaxProviderAvalara");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxProviderAvalara;
      return this.apiClient.callApi(
        '/tax/providers/avalara', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderSelf operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderSelf} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the Self tax provider
     * Update the Self tax provider. 
     * @param {module:com.ultracart.admin.v2.models/TaxProviderSelf} tax_provider_self TaxProviderSelf object
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderSelf}
     */
    updateTaxProviderSelf(tax_provider_self, callback) {
      let postBody = tax_provider_self;
      // verify the required parameter 'tax_provider_self' is set
      if (tax_provider_self === undefined || tax_provider_self === null) {
        throw new Error("Missing the required parameter 'tax_provider_self' when calling updateTaxProviderSelf");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxProviderSelf;
      return this.apiClient.callApi(
        '/tax/providers/self', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderSelfCity operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfCityCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxCity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a Self tax provider city
     * Updates a Self tax provider city. 
     * @param {String} city The city being updated.
     * @param {module:com.ultracart.admin.v2.models/TaxCity} tax_city tax city to be updated
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfCityCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxCity}
     */
    updateTaxProviderSelfCity(city, tax_city, callback) {
      let postBody = tax_city;
      // verify the required parameter 'city' is set
      if (city === undefined || city === null) {
        throw new Error("Missing the required parameter 'city' when calling updateTaxProviderSelfCity");
      }
      // verify the required parameter 'tax_city' is set
      if (tax_city === undefined || tax_city === null) {
        throw new Error("Missing the required parameter 'tax_city' when calling updateTaxProviderSelfCity");
      }

      let pathParams = {
        'city': city
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxCity;
      return this.apiClient.callApi(
        '/tax/providers/self/city/{city}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderSelfCountry operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfCountryCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxCountry} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a Self tax provider country
     * Updates a Self tax provider country. 
     * @param {String} countryCode The country code being updated.
     * @param {module:com.ultracart.admin.v2.models/TaxCountry} tax_country tax country to be updated
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfCountryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxCountry}
     */
    updateTaxProviderSelfCountry(countryCode, tax_country, callback) {
      let postBody = tax_country;
      // verify the required parameter 'countryCode' is set
      if (countryCode === undefined || countryCode === null) {
        throw new Error("Missing the required parameter 'countryCode' when calling updateTaxProviderSelfCountry");
      }
      // verify the required parameter 'tax_country' is set
      if (tax_country === undefined || tax_country === null) {
        throw new Error("Missing the required parameter 'tax_country' when calling updateTaxProviderSelfCountry");
      }

      let pathParams = {
        'countryCode': countryCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxCountry;
      return this.apiClient.callApi(
        '/tax/providers/self/country/{countryCode}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderSelfCounty operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfCountyCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxCounty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a Self tax provider county
     * Updates a Self tax provider county. 
     * @param {String} county The county being updated.
     * @param {module:com.ultracart.admin.v2.models/TaxCounty} tax_county tax county to be updated
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfCountyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxCounty}
     */
    updateTaxProviderSelfCounty(county, tax_county, callback) {
      let postBody = tax_county;
      // verify the required parameter 'county' is set
      if (county === undefined || county === null) {
        throw new Error("Missing the required parameter 'county' when calling updateTaxProviderSelfCounty");
      }
      // verify the required parameter 'tax_county' is set
      if (tax_county === undefined || tax_county === null) {
        throw new Error("Missing the required parameter 'tax_county' when calling updateTaxProviderSelfCounty");
      }

      let pathParams = {
        'county': county
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxCounty;
      return this.apiClient.callApi(
        '/tax/providers/self/county/{county}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderSelfPostalCode operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfPostalCodeCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxPostalCode} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a Self tax provider postalCode
     * Updates a Self tax provider postalCode. 
     * @param {String} postal_code The postal code being updated.
     * @param {module:com.ultracart.admin.v2.models/TaxPostalCode} tax_postal_code tax postal code to be updated
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfPostalCodeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxPostalCode}
     */
    updateTaxProviderSelfPostalCode(postal_code, tax_postal_code, callback) {
      let postBody = tax_postal_code;
      // verify the required parameter 'postal_code' is set
      if (postal_code === undefined || postal_code === null) {
        throw new Error("Missing the required parameter 'postal_code' when calling updateTaxProviderSelfPostalCode");
      }
      // verify the required parameter 'tax_postal_code' is set
      if (tax_postal_code === undefined || tax_postal_code === null) {
        throw new Error("Missing the required parameter 'tax_postal_code' when calling updateTaxProviderSelfPostalCode");
      }

      let pathParams = {
        'postal_code': postal_code
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxPostalCode;
      return this.apiClient.callApi(
        '/tax/providers/self/postalCode/{postal_code}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderSelfState operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfStateCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxState} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a Self tax provider state
     * Updates a Self tax provider state. 
     * @param {String} stateCode The state code being updated.
     * @param {module:com.ultracart.admin.v2.models/TaxState} tax_state tax state to be updated
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSelfStateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxState}
     */
    updateTaxProviderSelfState(stateCode, tax_state, callback) {
      let postBody = tax_state;
      // verify the required parameter 'stateCode' is set
      if (stateCode === undefined || stateCode === null) {
        throw new Error("Missing the required parameter 'stateCode' when calling updateTaxProviderSelfState");
      }
      // verify the required parameter 'tax_state' is set
      if (tax_state === undefined || tax_state === null) {
        throw new Error("Missing the required parameter 'tax_state' when calling updateTaxProviderSelfState");
      }

      let pathParams = {
        'stateCode': stateCode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxState;
      return this.apiClient.callApi(
        '/tax/providers/self/state/{stateCode}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderSovos operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSovosCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderSovos} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the Sovos tax provider
     * Update the Sovos tax provider. 
     * @param {module:com.ultracart.admin.v2.models/TaxProviderSovos} tax_provider_sovos TaxProviderSovos object
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderSovosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderSovos}
     */
    updateTaxProviderSovos(tax_provider_sovos, callback) {
      let postBody = tax_provider_sovos;
      // verify the required parameter 'tax_provider_sovos' is set
      if (tax_provider_sovos === undefined || tax_provider_sovos === null) {
        throw new Error("Missing the required parameter 'tax_provider_sovos' when calling updateTaxProviderSovos");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxProviderSovos;
      return this.apiClient.callApi(
        '/tax/providers/sovos', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderTaxJar operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderTaxJarCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderTaxJar} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the TaxJar tax provider
     * Update the TaxJar tax provider. 
     * @param {module:com.ultracart.admin.v2.models/TaxProviderTaxJar} tax_provider_taxJar TaxProviderTaxJar object
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderTaxJarCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderTaxJar}
     */
    updateTaxProviderTaxJar(tax_provider_taxJar, callback) {
      let postBody = tax_provider_taxJar;
      // verify the required parameter 'tax_provider_taxJar' is set
      if (tax_provider_taxJar === undefined || tax_provider_taxJar === null) {
        throw new Error("Missing the required parameter 'tax_provider_taxJar' when calling updateTaxProviderTaxJar");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxProviderTaxJar;
      return this.apiClient.callApi(
        '/tax/providers/taxjar', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateTaxProviderUltraCart operation.
     * @callback module:com.ultracart.admin.v2/TaxApi~updateTaxProviderUltraCartCallback
     * @param {String} error Error message, if any.
     * @param {module:com.ultracart.admin.v2.models/TaxProviderUltraCart} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update the UltraCart tax provider
     * Update the UltraCart tax provider. 
     * @param {module:com.ultracart.admin.v2.models/TaxProviderUltraCart} tax_provider_ultracart TaxProviderUltraCart object
     * @param {module:com.ultracart.admin.v2/TaxApi~updateTaxProviderUltraCartCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.ultracart.admin.v2.models/TaxProviderUltraCart}
     */
    updateTaxProviderUltraCart(tax_provider_ultracart, callback) {
      let postBody = tax_provider_ultracart;
      // verify the required parameter 'tax_provider_ultracart' is set
      if (tax_provider_ultracart === undefined || tax_provider_ultracart === null) {
        throw new Error("Missing the required parameter 'tax_provider_ultracart' when calling updateTaxProviderUltraCart");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['ultraCartOauth', 'ultraCartSimpleApiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TaxProviderUltraCart;
      return this.apiClient.callApi(
        '/tax/providers/ultracart', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
